[workspace]
members = [
    "database", 
    "errors",
]

[package]
name = "backend"
version = "0.1.0"
edition = "2024"
authors = ["Selendra"]

[dependencies]
axum = { workspace = true }
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }
tower = { workspace = true }
surrealdb = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }

[workspace.dependencies]
axum = "0.8.1"
anyhow = "1.0.97"
serde = "1.0.219"
async-graphql-axum = "7.0.16"
async-graphql = { version = "7.0.16", features = ["chrono"] }
tower = { version = "0.5.2" }
surrealdb = { version = "2.2.1" }
tokio = { version = "1.44.1", features = [
    "rt",
    "rt-multi-thread",
    "macros"
] }
tower-http = { version = "0.6.2", features = [
    "trace",
    "cors",
    "compression-gzip",
    "catch-panic",
    "timeout",
    "limit",
    "request-id",
] }

stablemint-surrealdb = { path = "database" }
stablemint-error = { path = "errors" }

