services:
  surrealdb1:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb1
    command: start --user root --pass root memory
    ports:
      - "4000:8000"
    volumes:
      - ./.local/surrealdb1-data:/data
    networks:
      - app-network
    restart: unless-stopped

  surrealdb2:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb2
    command: start --user root --pass root memory
    ports:
      - "4001:8000"
    volumes:
      - ./.local/surrealdb2-data:/data
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis_secure_password
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_secure_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    restart: unless-stopped
    volumes:
      - ./.local/vault/config:/vault/config
      - ./.local/vault/data:/vault/data
      - ./.local/vault/logs:/vault/logs
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    entrypoint: vault server -config=/vault/config/vault.json
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge