services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - surrealdb_data:/var/lib/surrealdb
    environment:
      - SURREALDB_AUTH=root:root
      - SURREALDB_DB=selendraDB
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis_secure_password
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_secure_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  surrealdb_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge