services:
  surrealdb:
    image: surrealdb/surrealdb:v2
    container_name: surrealdb
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - surrealdb_data:/var/lib/surrealdb
    environment:
      - SURREALDB_AUTH=root:root
      - SURREALDB_DB=selendraDB
    restart: unless-stopped

volumes:
  surrealdb_data:
    driver: local
