[package]
name = "stablemint-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
argon2 = { workspace = true }
stablemint-error = { workspace = true }