use crate::{middleware::auth::jwt::JwtService, schema::ApiSchema};
use app_error::AppResult;
use async_graphql::http::GraphiQLSource;
use async_graphql_axum::{GraphQLRequest, GraphQLResponse};
use axum::{
    extract::Extension,
    http::{HeaderMap, header},
    response::{Html, IntoResponse},
};
use std::sync::Arc;

use super::auth::AuthService;

// Handler for GraphQL POST requests with authentication
pub async fn graphql_handler(
    schema: Extension<ApiSchema>,
    jwt_service: Extension<Arc<JwtService>>,
    auth_service: Extension<Arc<AuthService>>,
    headers: HeaderMap,
    req: GraphQLRequest,
) -> AppResult<GraphQLResponse> {
    // Create a new request builder for modifying the GraphQL request
    let mut req_builder = req.into_inner();

    // IMPORTANT: Add auth service to the request context
    req_builder = req_builder.data(Arc::clone(&auth_service));

    // Check for authorization header
    if let Some(auth_header) = headers.get(header::AUTHORIZATION) {
        if let Ok(auth_str) = auth_header.to_str() {
            if auth_str.starts_with("Bearer ") {
                let token = &auth_str["Bearer ".len()..];

                // Validate the token
                if let Ok(claims) = jwt_service.validate_token(token) {
                    // Add the claims to the request data
                    req_builder = req_builder.data(claims);
                }
            }
        }
    }

    // Execute the GraphQL request
    let response = schema.execute(req_builder).await;

    Ok(response.into())
}

// Handler for GraphQL playground UI
pub async fn graphql_playground() -> impl IntoResponse {
    Html(GraphiQLSource::build().endpoint("/graphql").finish())
}

// Simple health check endpoint
pub async fn health_check() -> impl IntoResponse {
    (
        axum::http::StatusCode::OK,
        Html(
            "<html>
                <head>
                    <title>Health Check</title>
                    <style>
                        body {
                            font-family: Arial, sans-serif;
                            background-color: #f4f4f9;
                            color: #333;
                            text-align: center;
                            padding: 50px;
                        }
                        h1 {
                            color: green;
                        }
                        p {
                            font-size: 18px;
                        }
                    </style>
                </head>
                <body>
                    <h1>System Health Check</h1>
                    <p>Status: <strong>OK</strong></p>
                    <p>The system is up and running smoothly. All services are operational.</p>
                    <p>If you encounter any issues, please contact the support team.</p>
                    <footer>
                        <p>Generated by Axum Health Service</p>
                    </footer>
                </body>
            </html>",
        ),
    )
}
