use crate::error::{AppError, AppResult};
use crate::schema::ApiSchema;
use async_graphql_axum::{GraphQLRequest, GraphQLResponse};
use axum::response::Html;
use axum::{extract::Extension, response::IntoResponse};

// Handler for GraphQL POST requests with error handling
pub async fn graphql_handler(
    schema: Extension<ApiSchema>,
    req: GraphQLRequest,
) -> AppResult<GraphQLResponse> {
    let response = schema.execute(req.into_inner()).await;

    // Check for GraphQL errors and convert to AppError if needed
    if response.is_err() {
        return Err(AppError::GraphQLError(response.errors[0].clone().into()));
    }

    Ok(response.into())
}

// Handler for GraphQL playground UI
pub async fn graphql_playground() -> impl IntoResponse {
    axum::response::Html(async_graphql::http::playground_source(
        async_graphql::http::GraphQLPlaygroundConfig::new("/graphql"),
    ))
}

// Simple health check endpoint
pub async fn health_check() -> impl IntoResponse {
    (
        axum::http::StatusCode::OK,
        Html(
            "<html>
                <head>
                    <title>Health Check</title>
                    <style>
                        body {
                            font-family: Arial, sans-serif;
                            background-color: #f4f4f9;
                            color: #333;
                            text-align: center;
                            padding: 50px;
                        }
                        h1 {
                            color: green;
                        }
                        p {
                            font-size: 18px;
                        }
                    </style>
                </head>
                <body>
                    <h1>System Health Check</h1>
                    <p>Status: <strong>OK</strong></p>
                    <p>The system is up and running smoothly. All services are operational.</p>
                    <p>If you encounter any issues, please contact the support team.</p>
                    <footer>
                        <p>Generated by Axum Health Service</p>
                    </footer>
                </body>
            </html>",
        ),
    )
}
