[package]
name = "stablemint-surrealdb"
version = "0.1.0"
edition = "2024"

[dependencies]
surrealdb = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stablemint-error = { workspace = true }
tracing = { workspace = true }
dotenv = { workspace = true }