[package]
name = "app-error"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

async-graphql = { workspace =  true }
axum = { workspace =  true }